name: CI/CD

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install nim
      run: |
        curl https://nim-lang.org/choosenim/init.sh -sSf > install.sh
        chmod +x install.sh
        ./install.sh -y
        export PATH=/home/runner/.nimble/bin:$PATH
        choosenim devel --latest
    - name: Build
      run: ./build.sh
